Fix types for epicStrategyBuilder
TimeTac/js-core pull request #13
Opened 2021-02-01 13:03 UTC by sergej-tschak

- PR with @benj56 improvements for #7

2021-02-01 13:06 UTC, AlGvrl approved these changes

2021-02-01 13:29 UTC, haubitzer requested changes

2021-02-01 13:29 UTC, haubitzer commented on src/entities/absenceTypes/absenceTypesEpic.ts
> +  { absenceTypes: true },
Please, remove as BlockingResources also from the calls, users and projects ...

2021-02-01 13:29 UTC, haubitzer commented on src/deltaSync/deltaSyncEpic.ts
> +  const hasResults = Boolean(response && response.results && response.results.length && upsertAction(response.results as R[]));
This will not work, because now hasResults is always a boolean, and before it was the action or false

2021-02-01 15:20 UTC, sergej-tschak commented on src/entities/absenceTypes/absenceTypesEpic.ts
> +  { absenceTypes: true },
removed

2021-02-01 15:20 UTC, sergej-tschak commented on src/deltaSync/deltaSyncEpic.ts
> +  const hasResults = Boolean(response && response.results && response.results.length && upsertAction(response.results as R[]));
This one was rolled back

2021-02-01 16:57 UTC, haubitzer approved these changes

2021-02-02 08:34 UTC, benj56 approved these changes

2021-02-02 08:34 UTC, merged