Start task at login
TimeTac/js-core pull request #28
Opened 2021-02-17 13:05 UTC by sergej-tschak

- fire allResourcesCompleted additionally after rehydrate
- add epic for start task on allResourcesCompleted (login, app start)
- add tests for initial load epic & slice

2021-02-17 13:33 UTC, benj56 requested changes
We should start the task at app launch, I think neither `allResourcesCompleted` of initialSync or `rehydrate` is suitable. We need to do that after the app was started and a DeltaSync has completed so that we know whether a task is running. I think it needs a new sort of event, something like `appLaunched` that is dispatched after app launch and the first delta sync

2021-02-17 17:07 UTC, AlGvrl commented on src/login/loginSlice.ts
> +      // app is fully functional - fires after first deltaSync be finished
```suggestion
      // app is fully functional - fires after first deltaSync is finished
```

2021-02-17 17:07 UTC, AlGvrl commented on src/deltaSync/deltaSyncEpic.ts
> +const appLaunchedEpic = (action$: Observable<Action>, _state$: StateObservable<RootState>) =>
I will be honest, I'm not quite sure why is this needed.
I imagined we would be dispatching the `appLaunched()` actions manually, wherever it is appropriate in the app (just because these "wherever it's appropriate" would probably differ for desktop and web).

However, @benj56 's review was about this, if I understand it correctly, so if he says it's good, I'll just take his word for it.

2021-02-17 17:34 UTC, benj56 commented on src/deltaSync/deltaSyncEpic.ts
> +const appLaunchedEpic = (action$: Observable<Action>, _state$: StateObservable<RootState>) =>
I agree, it makes sense to dispatch `appLaunched` from the apps. 

How about:
 `login/appLaunched` => `timeTracking.autoStartPending = true` (reducer)
 `deltaSync/received` => `if(state.timeTracking.autoStartQueued) dispatch(timetracking/start)` (epic)
`timeTracking/start` => `timeTracking.autoStartPending = false` (reducer) 

Would that make sense?

2021-02-17 19:53 UTC, sergej-tschak commented on src/deltaSync/deltaSyncEpic.ts
> +const appLaunchedEpic = (action$: Observable<Action>, _state$: StateObservable<RootState>) =>
ok, will explain. with first comment @benj56 was correct we need to wait till deltaSync happens as we can not just trigger timetracking/start or something similar exactly after app is started. for some pending flag I would say it just brings even more complexity.

Idea here is to have flag login.launched which should be set to true after the first deltaSync request is handled (initial value in state is false). For desktop I need extra appQuit to set this flag to false when user closes app / main window. this you will see in second PR I will open for desktop (change is already pushed)

2021-02-17 22:23 UTC, sergej-tschak commented on src/initialLoad/initialLoadEpic.test.ts
> +import { AbsenceType, GeneralSetting, Project, RequestParamsBuilder, Task, TimeTracking, User } from '../../../js-client-library';
improved

2021-02-17 22:24 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +        const task = taskSelectors.selectById(_state$.value, loggedInUser.start_task_at_login);
improved

2021-02-17 22:25 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +        if (task && !task.is_paid_non_working && !task.is_hidden && !task.is_blocked && task.is_startable) {
I will keep it for now as it is as it is used only once in the current package

2021-02-17 23:04 UTC, sergej-tschak commented on src/initialLoad/initialLoadEpic.test.ts
> +  test('completedEpic results in allResourcesCompleted', async (done) => {
improved

2021-02-17 23:05 UTC, sergej-tschak commented on src/initialLoad/initialLoadEpic.test.ts
> +  test('completedEpic results with EMPTY', async (done) => {
improved a bit tests naming

2021-02-17 23:07 UTC, sergej-tschak commented on src/login/loginSlice.ts
> +  launched?: boolean;
this question mark helps me that way that I don't need to open one more PR for web app to fix typescript issues for tests

2021-02-18 08:26 UTC, AlGvrl commented on src/login/loginSlice.ts
> +  launched?: boolean;
On one hand, I know your pain, but on the other hand having "I don't know" be a possible answer for "Did the app load?" does not seem reasonable to me.

2021-02-18 08:27 UTC, AlGvrl approved these changes

2021-02-18 08:37 UTC, sergej-tschak commented on src/login/loginSlice.ts
> +  launched?: boolean;
uff .. will remove question mark and fix tests in all repos we have

2021-02-18 09:59 UTC, tomi-timetac commented on src/login/loginSlice.test.ts
> +  test('Receiving appQuit action sets boolean flag to false (action is used in desktop app)', async (done) => {
remove (action is used in desktop app)

2021-02-18 11:58 UTC, sergej-tschak commented on src/login/loginSlice.test.ts
> +  test('Receiving appQuit action sets boolean flag to false (action is used in desktop app)', async (done) => {
improved

2021-02-18 12:19 UTC, benj56 commented on src/deltaSync/deltaSyncEpic.ts
> +const appLaunchedEpic = (action$: Observable<Action>, _state$: StateObservable<RootState>) =>
I prefer the structure described above with the app dispatching `login/appLaunched` instead of doing that in Core after DeltaSync. With that, we don't need the `appQuit` action

2021-02-18 15:33 UTC, benj56 approved these changes

2021-02-23 10:26 UTC, tomi-timetac approved these changes

2021-02-23 10:33 UTC, merged