Add autoStartTaskSelected and autoStartTaskCleared
TimeTac/js-core pull request #29
Opened 2021-02-22 15:08 UTC by haubitzer

2021-03-01 14:06 UTC, benj56 requested changes

2021-03-01 14:06 UTC, benj56 commented on src/entities/users/usersSlice.ts
> +    partialUpdated: (_state, _action: PayloadAction<PartialUpdate<User>>) => undefined,
In the ticket description we planned `users/autoStartTaskSelected` => network request => `users/upsert` for now. 
When we remove `users/upsert`, I'd think we would do something like `users/autoStartTaskSelected` => network request => `users/autoStartTaskSelectedReceived`. 

From my perspective `users/autoStartTaskSelected` => `users/partialUpdated` => network request => `users/upsert` is a step in the wrong direction as the number of actions needed to get the job done increases. The `users/partialUpdated` on its own would make no sense, it always needs an actual event or in other words action that triggers it. Let's remove that `partialUpdated` action and keep the generic approach inside the epics. 

I'm thinking something like:
``` TypeScript
const autoStartTaskSelectedEpic = (action$: Observable<Action>, state$: StateObservable<RootState>) =>
  action$.pipe(
    filter(usersSlice.actions.autoStartTaskSelected.match),
    switchMap(action => updateAutoStartTask(usersSelectors.selectLoggedIn(state$.value), action.payload, usersSlice.upsert))
  );
```

What would you think about that?

2021-03-01 14:36 UTC, haubitzer commented on src/entities/users/usersSlice.ts
> +    partialUpdated: (_state, _action: PayloadAction<PartialUpdate<User>>) => undefined,
Just to be clear... You want to remove the `partialUpdate` action to have one action less because it not connected to an "user action" and make the request via a function call. Also, you want to have for every "user action" that triggers a request to have its own received action?

2021-03-01 14:55 UTC, benj56 commented on src/entities/users/usersSlice.ts
> +    partialUpdated: (_state, _action: PayloadAction<PartialUpdate<User>>) => undefined,
Yes, I think each request should have a received action that still makes it clear where the request came from when we handle the results

2021-03-01 15:10 UTC, haubitzer commented on src/entities/users/usersSlice.ts
> +    partialUpdated: (_state, _action: PayloadAction<PartialUpdate<User>>) => undefined,
Okay. Basically, this means that we need to remove epicStrategyBuilder because the syncStrategy doesn't work with this logic.

2021-03-01 16:07 UTC, haubitzer commented on src/entities/users/usersSlice.ts
> +    partialUpdated: (_state, _action: PayloadAction<PartialUpdate<User>>) => undefined,
I created a story for removing it.

2021-03-02 08:15 UTC, benj56 approved these changes

2021-03-02 14:15 UTC, merged