Remove separate logged-in user entity from state
TimeTac/js-core pull request #31
Opened 2021-02-23 11:54 UTC by benj56

2021-02-23 15:02 UTC, haubitzer requested changes

2021-02-23 15:02 UTC, haubitzer commented on src/entities/users/usersAdapter.ts
> +  (loggedIn, users) => {
maybe we could use here _selectById_  ... but I am not sure

2021-02-23 16:45 UTC, benj56 commented on src/entities/users/usersAdapter.ts
> +  (loggedIn, users) => {
Tried to do that but I see no way to use the id returned by the first selector in the second selector, seems to be only possible in the combiner

2021-02-23 16:49 UTC, benj56 commented on src/entities/users/usersSlice.ts
> +  extraReducers: (builder) => {
I think it would make sense if `login.userId` is then moved to `users.loggedInId` but I'm unsure whether it's an improvement

2021-02-23 16:52 UTC, benj56 commented on src/login/loginSlice.ts
>  export type LoginState = {
I wouldn't be against it but so far everything in login seems at least somewhat related to login

2021-02-23 17:26 UTC, haubitzer approved these changes
LGTM, I only added two general comments about the design.

2021-02-23 17:26 UTC, haubitzer commented on src/login/loginSlice.ts
>  export type LoginState = {
Most of it is fine, but _rehydrated_ and _launching_ are IMO not part of the login process because if they would you would be able to argue that the initial load is also part of the login process.

2021-02-23 17:26 UTC, haubitzer commented on src/entities/users/usersSlice.ts
> +  extraReducers: (builder) => {
users.loggedInId would make no sense... 

I don't like the idea that we make a request in loginSlice that updates the usersStore via a side effect and not vice versa. Make the request as a UserSlice action (users/requestUsersMe) and then update the _login.userId_ via an _extrareducer_ or an explicit action. The benefit would be that we keep all request calls in one file.

2021-02-23 17:26 UTC, haubitzer commented on src/entities/users/usersAdapter.ts
> +  (loggedIn, users) => {
Mhhh... if I have time I will take a look at this. Because sooner or later we need to have logic like that.

2021-02-24 08:00 UTC, sergej-tschak approved these changes

2021-02-24 08:04 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +      const loggedInUser = userSelectors.loggedIn(state$.value);
@sergej-tschak it was already fixed, for some reason, you were looking at an old commit.

```
      const loggedInUser = state$.value.core.login.user;
      const loggedInUser = userSelectors.selectLoggedIn(state$.value);
```

2021-02-26 13:04 UTC, merged