Timer update error handling
TimeTac/js-core pull request #37
Opened 2021-02-26 15:19 UTC by tjb7

2021-02-26 15:23 UTC, tjb7 commented
Tests still need to be fixed, but have made this draft pull request since it is related to a subtask I'm completing

2021-03-04 08:59 UTC, tjb7 commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +            console.log(`TJB: Action has id ${action.payload.error_ref_id}`);
get rid of log

2021-03-04 09:18 UTC, tjb7 commented on src/error/errorSlice.ts
> -          console.error('Not a string: ', action.payload);
git rid of log

2021-03-04 09:18 UTC, tjb7 commented on src/error/errorSlice.ts
> -          console.error('Not a string: ', action.payload);
Actually this should be here.

2021-03-04 09:50 UTC, tomi-timetac commented on src/error/errorSlice.ts
> +      //eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
any reason you removed the action.payload.ErrorMessage != null check and added the lint exception?

2021-03-04 09:51 UTC, tomi-timetac commented on src/utils/utilTypes.ts
> +  error_ref_id: number;
any reason its not camel case?

2021-03-04 13:22 UTC, haubitzer requested changes

2021-03-04 13:22 UTC, haubitzer commented on src/utils/dateUtils.ts
> +  unixTimestamp(): number {
This function should be removed or changed. It looks like a function that can and will be misused.

2021-03-04 13:22 UTC, haubitzer commented on src/entities/successfulRequestsWithClientId/successfulRequestWithClientIdAdapter.ts
> +  (state: RootState) => state.core.entities.successfulRequestWithClientId
I am not sure if we want to have "successfulRequestWithClientId" in the entities structure. Because at the moment we have resource/endpoint is entities and everything that isn't a resource is somewhere else. I think that logic makes sense and we should keep it.

maybe something like that:
`state.core.logs.successfulRequestWithClientId`. and also we could move "state.core.error" there as well `state.core.logs.error`

2021-03-04 20:45 UTC, tjb7 commented on src/utils/dateUtils.ts
> +  unixTimestamp(): number {
how so? It is a unix timestamp ... how is it more prone to misuse than anything else?

2021-03-04 20:45 UTC, tjb7 commented on src/error/errorSlice.ts
> +      //eslint-disable-next-line @typescript-eslint/strict-boolean-expressions
demonstrated problems live

2021-03-04 20:47 UTC, tjb7 commented on src/entities/successfulRequestsWithClientId/successfulRequestWithClientIdAdapter.ts
> +  (state: RootState) => state.core.entities.successfulRequestWithClientId
Yes, I think this makes sense, but I will not change it now, because that kind of change might not be needed (or greater change may be needed) as we modify our approach.

2021-03-04 20:48 UTC, tjb7 commented on src/utils/utilTypes.ts
> +  error_ref_id: number;
in general, the fields we add to requests are not in camel case, but of course, this is not added to a request so it could be.

2021-03-05 09:18 UTC, tomi-timetac approved these changes

2021-03-05 11:30 UTC, tomi-timetac approved these changes

2021-03-08 07:21 UTC, whosshell commented on src/error/errorSlice.ts
> +      console.log(action);
Can be removed.

2021-03-08 07:23 UTC, whosshell commented on src/error/errorSlice.ts
> +        throw new Error('Error message string could not be determined.');
We don't want app to crash, rather log it with console.error()

2021-03-08 07:33 UTC, whosshell approved these changes
Will have to be adapted in future versions

2021-03-08 07:50 UTC, haubitzer commented on src/utils/dateUtils.ts
> +  unixTimestamp(): number {
We can not use the unixTimestamp for sorting/ordering because it is not unique. Because the local time can be changed by the system and so would the unixTimestamp as well.
Also, we should not share the unixtimestamp with the server, because we can't trust the local client time.

2021-03-08 07:52 UTC, haubitzer approved these changes

2021-03-08 08:01 UTC, tomi-timetac commented on src/utils/dateUtils.ts
> +  unixTimestamp(): number {
we changed it to use uuid instead. The unixTImestamp is now just a helper function.

2021-03-08 08:01 UTC, whosshell approved these changes

2021-03-08 08:26 UTC, merged