Replace LTT epics & slices with selectors
TimeTac/js-core pull request #5
Opened 2021-01-27 14:39 UTC by sergej-tschak

2021-01-27 15:21 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +  timetrackings.find((timetracking) => timetracking.status === 1)
Create enums for status in the CL

2021-01-27 15:25 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +        map((response: TimeTracking | undefined) => timeTrackingsSlice.actions.receiveCurrentRunning(response))
don't fire the action is you have no data, because nothing will change

2021-01-27 15:26 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +          return response.affected?.timeTrackings
there is a better way to doing this logic, See the pull request from deltaSync

2021-01-27 15:27 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +                timeTrackingsSlice.actions.setOne(response.affected.timeTrackings[0]),
also, what happens if you have more than one affected? maybe use receiveRead

2021-01-27 15:31 UTC, haubitzer commented on src/index.ts
> +    timetrackings: { ...timetrackingSelectors, currentRunningTimeTrackingSelector, previousRunningTimeTrackingSelector },
We should more the merging of selects to the file where they are and not merge them here

2021-01-27 15:34 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +export const previousRunningTimeTrackingSelector: (state: RootState) => TimeTracking | undefined = createSelector(
Why do we need to have this selector? it looks a little bit overcomplex.

2021-01-27 15:36 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +  timetrackings.find((timetracking) => timetracking.status === 1)
this can fail. because there can be the case where we have more than one status === 1 in our store... also there should be the possibility to give the userID as argument

2021-01-27 15:37 UTC, haubitzer requested changes
added a few comments already

2021-01-27 15:59 UTC, benj56 commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +      : undefined;
We could rewrite it with a for loop and if's for more readability. And a bit improved performance I believe due to only doing one instead of two date parses:

```suggestion
    if(filteredTimetrackings.length === 0) return undefined;

    let latest = filteredTimetrackings[0];
    let latestDate = dateUtils.parseServerDateTime(latest.end_time as string);

    for (let i = 1; i < filteredTimetrackings.length; i++) {
      const endDate = dateUtils.parseServerDateTime(filteredTimetrackings[i].end_time as string);

      if(endDate > latestDate) {
        latest = filteredTimetrackings[i];
        latestDate = endDate;
      }
    }
    
    return latest;
```

2021-01-27 16:27 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +      : undefined;
still, readability is not perfect maybe something like that would be better

`return filteredTimetrackings.sort((a,b) => a.end_time - b.end_time).pop();`

For sure performance is not perfect because we a sorting and picking, and not just picking...

But the real question is: What is the purpose of this selector? because I don't know why you want to select the last running timetracking of some random user.

2021-01-28 09:26 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +  timetrackings.find((timetracking) => timetracking.status === 1)
looks like there is no good way to have user_id as dynamic argument for selector. selector can work only with data saved to store (https://github.com/reduxjs/reselect#q-how-do-i-create-a-selector-that-takes-an-argument). here I will change to logged in user. and later when we will need to have case with dynamically changed users we will create new selector or refactor current one.

2021-02-01 07:20 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +  requestStartTimeTrackingEpic,
epics were renamed

2021-02-01 07:21 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +        map((response: TimeTracking | undefined) => timeTrackingsSlice.actions.receiveCurrentRunning(response))
this fragment was refactored, so there is no more action with undefined payload

2021-02-01 07:22 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +          return response.affected?.timeTrackings
this fragment was refactored

2021-02-01 07:25 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +const requestCurrentRunningEpic = (action$: Observable<Action>, state$: StateObservable<RootState>) =>
we need this action at least once, because we need to render current running timetracking when dashboard is loaded. this happens, because timetrackings are not included in initial sync. we might refactor it again when DeltaSync is ready

2021-02-01 07:29 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +const requestCurrentRunningEpic = (action$: Observable<Action>, state$: StateObservable<RootState>) =>
all current were not in scope, but agree, it might be needed for status overview widget. will include this change to refactoring of status overview

2021-02-01 07:32 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +export const previousRunningTimeTrackingSelector: (state: RootState) => TimeTracking | undefined = createSelector(
we need it to get timetracking which was running before current running. complexity was reduced, we applied changes suggested by Benjamin

2021-02-01 07:34 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +      : undefined;
@benj56 suggestion was taken to replace solution with .reduce()

2021-02-01 07:38 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +      : undefined;
we need selector as we have start & stop & pause buttons and we need to know which timetracking was running before for all possible combinations of user behavior scenarios

2021-02-01 08:38 UTC, haubitzer requested changes

2021-02-01 08:38 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +export const previousRunningTimeTrackingSelector: (state: RootState) => TimeTracking | undefined = createSelector(
I think this selector will not work as it should. It will return a timetracking that has the highest end_time and is not a break... 

It doesn't check if the user of the result is the logged-in user.
It doesn't check if the task of the result is startable.
It returns undefined if there is no time tracking in the store.

but all of this makes no sense because what we really want is the last task the logged-in user stoped. And this is something only the backend can answer correctly. The frontend will not be able to do that without a request, the frontend only can guess the task, and this is not good enough here.

2021-02-01 08:38 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +            timeTrackingsSlice.actions.receiveCreate(response.results[0]),
`response.results[0]` can fail if the array is empty, maybe use `action.upsert`

2021-02-01 08:38 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsSlice.ts
> +    requestStartTimeTracking: (_state, _action: PayloadAction<StartTimeTrackingData>) => {},
rename to `requestStartTimeTracking` to `requestStart` ... same for stop

2021-02-01 08:38 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +export const timetrackingSelectors = { ...adapterSelectors, currentRunningTimeTrackingSelector, previousRunningTimeTrackingSelector };
maybe rename our selectors so they have the same style as adapterSelecotors..   `selectRunning` `selectPrevioursRunning`

2021-02-02 07:48 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +export const timetrackingSelectors = { ...adapterSelectors, currentRunningTimeTrackingSelector, previousRunningTimeTrackingSelector };
renamed

2021-02-02 07:48 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsSlice.ts
> +    requestStartTimeTracking: (_state, _action: PayloadAction<StartTimeTrackingData>) => {},
renamed

2021-02-02 10:34 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +export const selectRunning: (state: RootState) => TimeTracking | undefined = createSelector(
General Note: I am not sure if `createSelector` is the correct function, maybe we should use createDraftSafeSelector, so this selector is save when it is used in a reducer. (https://redux-toolkit.js.org/api/createSelector#createdraftsafeselector) 

Also, I think it would be possible to use an argument here for the user_id, because it is also possible for the selectById selector. See this example from redux-toolkit: 

 
 
    const selectId = (_: any, id: EntityId) => id

`const selectById = (entities: Dictionary<T>, id: EntityId) => entities[id]`

    if (!selectState) {
      return {
        selectIds,
        ...
        selectById: createDraftSafeSelector(
          selectEntities,
          selectId,
          selectById
        )
      }
    }`

2021-02-02 12:24 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +            timeTrackingsSlice.actions.receiveCreate(response.results[0]),
this one is changed to use upsert

2021-02-02 12:27 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +export const selectRunning: (state: RootState) => TimeTracking | undefined = createSelector(
Idea is good itself, but I prefer to have separate story for such refactoring. Or this could be included in refactoring of status overview widget

2021-02-02 12:31 UTC, sergej-tschak commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +export const previousRunningTimeTrackingSelector: (state: RootState) => TimeTracking | undefined = createSelector(
we have improved selector, but we did not get rid of it completely. at first load we fetch previous running timetracking for logged in user and later we rely on deltaSync which returns keeps timetrackings updated. And in this case this selector is needed as we filter store and watch it

2021-02-02 12:37 UTC, AlGvrl approved these changes

2021-02-02 12:39 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +export const selectRunning: (state: RootState) => TimeTracking | undefined = createSelector(
Yes, own PR is fine...but is something we need to check

2021-02-02 12:46 UTC, haubitzer commented on src/entities/timeTrackings/timeTrackingsEpic.ts
> +        ? [timeTrackingsSlice.actions.upsert(response.results), timeTrackingsSlice.actions.upsert(response.affected.timeTrackings)]
I am not sure if it can be a problem that these are two actions and not only one. Because this can have the effect that we have two timetrackings with status "Running" in the store for a short time. But I think for now it is fine.

2021-02-02 12:46 UTC, benj56 approved these changes
LGTM, just suggested some blank lines in that selector

2021-02-02 12:46 UTC, benj56 commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +    if (filteredTimetrackings.length === 0) return undefined;
```suggestion
    if (filteredTimetrackings.length === 0) return undefined;
    
```

2021-02-02 12:46 UTC, benj56 commented on src/entities/timeTrackings/timeTrackingsAdapter.ts
> +    let latestDate = dateUtils.parseServerDateTime(latest.end_time as string);
```suggestion
    let latestDate = dateUtils.parseServerDateTime(latest.end_time as string);
    
```

2021-02-02 12:46 UTC, haubitzer approved these changes

2021-02-03 07:54 UTC, merged