Paging via Strategy
TimeTac/js-core pull request #7
Opened 2021-01-28 10:06 UTC by haubitzer

2021-01-28 12:15 UTC, haubitzer commented on src/initialLoad/initialLoadEpic.ts
> +const INITIAL_PAGE_SIZE = 100;
Page size should be changed later to 2000 but at the moment it helps for tests/debugging

2021-01-29 14:08 UTC, benj56 requested changes
LGTM, fixed some types to get rid of the eslint disables/any. I committed the type fixes in that branch: implement-paging-via-epicStrategyBuilder-with-type-fixes

I think there are 2 problems we need to investigate next week before merging:

- placement of the catchError, I believe it breaks after the first error
- unserializable Actions

2021-01-29 14:08 UTC, benj56 commented on src/initialLoad/initialLoadEpic.ts
> +        absenceTypesSlice.actions.initialLoad(new RequestParams<AbsenceType>().limit(INITIAL_PAGE_SIZE)),
None of those will work in the desktop app due to the non-serializable actions problem

2021-01-29 16:53 UTC, haubitzer commented
@benj56 Thank you for your feedback. I like your changes. Please feel free to apply them and merge this story.

2021-02-09 10:29 UTC, benj56 approved these changes

2021-02-10 09:03 UTC, sergej-tschak approved these changes

2021-02-10 14:22 UTC, merged